#version: '3.8'

services:
  cms:
    build: ./cms
    container_name: moove-cms
    ports:
      - "1337:1337"
    volumes:
      - ./cms/public/uploads:/app/public/uploads
    env_file:
      - ./cms/.env.production
    depends_on:
      - moove-db
    restart: unless-stopped

  moove-db:
    image: mysql:8.0
    container_name: moove-db
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  moovetravel:
    build: ./mooveTravel
    container_name: moovetravel
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./mooveTravel:/app
    env_file:
      - ./mooveTravel/.env.production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: moove-nginx
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "3000:3000"
    depends_on:
      - moovetravel
      - cms
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email andrey@moov-travel.ru --agree-tos --no-eff-email --force-renewal -d moov-travel.ru
volumes:
  db_data: 