/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapi5SitemapPlugin from "strapi-5-sitemap-plugin/strapi-admin";
import emailDesigner5 from "strapi-plugin-email-designer-5/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.ts";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "strapi-5-sitemap-plugin": strapi5SitemapPlugin,
    "email-designer-5": emailDesigner5,
  },
});
